select * from MemberCreditCards;
select * from Members;
select * from Cities;
select * from MovieCopies;
select * from MovieRents;
select * from MovieRoles;
select * from MoviePhotos;
select * from ActorPhotos;
select * from MovieCharacters;
select * from GenreMovie;
select * from Movies;
select * from Genres;
select * from ImageGalleries;
select * from Actors;

delete from MemberCreditCards;
delete from Members;
delete from Cities;
delete from MovieRoles;
delete from MovieCopies;
delete from MoviePhotos;
delete from ActorPhotos;
delete from MovieCharacters;
delete from MovieRents;
delete from GenreMovie;
delete from Movies;
delete from Genres;
delete from ImageGalleries;
delete from Actors;